apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-jzkl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-jzkl
    app.kubernetes.io/part-of: test-app-qjgm
  name: test-component-jzkl
  namespace: build-e2e-hacbs-ojth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-jzkl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-jzkl
    spec:
      containers:
      - image: quay.io/psturc/test-images:f889a3ac9be24934868919b1188789da
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
